spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debezium_to_kudu?serverTimezone=Asia/Shanghai
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 9200

#logging:
#  level:
#    personal.leo.debezium_to_kudu.mapper: DEBUG

kudu:
  master-addresses: kudu1:7051,kudu2:7051,kudu3:7051
email:
  hostName: smtp.163.com
  from: youruser@163.com
  user: youruser@163.com
  password: yourpassword
  tos:
    - to@to.com