spring:
  datasource:
    url: jdbc:mysql://localhost:3306/debezium_to_kudu?serverTimezone=Asia/Shanghai
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10010

#logging:
#  level:
#    personal.leo.debezium_to_kudu.mapper: DEBUG

kudu:
  master-addresses: test01:7051,test02:7051,test03:7051
email:
  hostName: smtp.163.com
  from: ypshengxian@163.com
  user: ypshengxian@163.com
  password: YBYFNAGEYXJAGQMO
  tos:
    - liaochao@ypshengxian.com