spring:
  datasource:
    url: jdbc:mysql://datamaster01:3306/debezium_to_kudu
    username: root
    password: 1111
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 10010

#logging:
#  level:
#    personal.leo.debezium_to_kudu.mapper: DEBUG

kudu:
  master-addresses: kudu1:7051,kudu2:7051,kudu3:7051
email:
  hostName: smtp.163.com
  from: ypshengxian@163.com
  user: ypshengxian@163.com
  password: YBYFNAGEYXJAGQMO
  tos:
    - liaochao@ypshengxian.com